### ISSUE TITLE
Wiki has grammatical error on buildings with job capacities

### ISSUE THREAD

**Issue by Lonecorgi** [tfe2-wiki/tfe2-wiki.github.io#10]
![image](https://github.com/tfe2-wiki/tfe2-wiki.github.io/assets/91595658/4712a40c-09ef-41a7-87d9-f502402289f8)
(this image was found on the page about intergalactic library, but I have also seen this typo on Tree plantation, and computer chip factory)
Most pages I have seen that are about buildings with a job capacity have a spelling error. My guess is it was caused by the page generator.

**Comment by DT-is-not-available** [comment]
I can't seem to find where in the page generator is causing this, but I will look into this along with adding new buildings and other pages.

**Comment by DT-is-not-available** [comment]
This wiki page is being shut down due to difficulties contributing to it, and a lack of content. I will be moving everything to [the new wiki](https://tfe2.miraheze.org/wiki/Main_Page), which already has way more content and is way friendlier to contributors. Sorry for the inconvenience.
