### ISSUE TITLE
Final Earth 2 Updates

### ISSUE THREAD

**Issue by lowchain3071** [tfe2-wiki/tfe2-wiki.github.io#6]
On October 20 2022, the Final Earth 2 version of coolmath games updated, making the features match up to other versions. IN addition, we also forgot the fact that the itch.io version updated twice, once for the hackers/hippies, and i forgot the other one but we need to add an updates page to make sure people know what's going on.

**Comment by DT-is-not-available** [comment]
I'm currently working on a lot of other things right now so I probably won't have this done any time soon, feel free to make a pull request if you want though, as I agree discrepancies between different versions should probably be on there.
